### ISSUE TITLE
[Fix] 습관방 만들기 기능 오류 해결

### ISSUE THREAD

**Issue by L-j-h-c** [TeamSparker/Spark-iOS#206]
## 📌  Issue

- 습관방 만들기 기능 오류 해결

## 📝  To-do

- [ ] 습관방 만들기 기능 오류 해결

**Comment by hyun99999** [comment]
이거 시작하지 않던 오류인거죠? 됐다면 닫을까요?

**Comment by L-j-h-c** [comment]
@hyun99999 넵 이거 해결된 것 같아서 닫겠습니다!!
