### ISSUE TITLE
[Design] 피드 하단 inset 조절 및 커스텀 탭바에 맞추기

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#412]
## 🛠 Issue

피드 하단 inset 조절 및 커스텀 탭바에 맞추기
- 현규선배 이슈 제목 훔쳐왔슴니다 ㅎㅅㅎ

## 📝 To-do

- [x] inset 조정

**Comment by hyun99999** [comment]
ㅋㅋㅋㅋㅋㅋㅋ ㅇㅅaㅇ
