### ISSUE TITLE
[Bug] 습관방 나가기 후 토스트메세지 안뜨는 문제

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#612]
## 🛠 Issue

습관방 나가기 후 습관방을 나갔다는 토스트메세지 등장하는 기능을 구현해뒀는데, 뜨지 않습니다. T^T
https://user-images.githubusercontent.com/81167570/167879005-5c9409d8-25d0-4bf4-9eef-0cab14c66531.MP4

## 📝 To-do

- [x] 왜인지 알아보기
- [x] 해결해보기

**Comment by hyun99999** [comment]
진짜네...? 아이고야 왜그랴...
