### ISSUE TITLE
[Refactor] FeedVC 리펙토링

### ISSUE THREAD

**Issue by yangsubinn** [TeamSparker/Spark-iOS#625]
## 🛠 Issue

데이터 가공하는 부분 위주로 리팩해보겠습니다.
서버에서 받아오는 데이터를 분류하는 작업을 어쩔 수 없이 필요해서 ..
일단은 생각나는 것은 ViewModel 등을 통해 역할에 따라 분리하고 VC의 기다란 코드를 최대한 줄여보는 방식으로 생각중입니다.
일단 생각까지만 했습니다

## 📝 To-do

- [x] FeedVC 싹 밀어보기🔫

**Comment by hyun99999** [comment]
그대의 용기에 치얼ㄹ...스....
