### ISSUE TITLE
[Chore] 앱 아이콘 단순화

### ISSUE THREAD

**Issue by hyun99999** [TeamSparker/Spark-iOS#645]
## 🛠 Issue

- 기존에는 앱 아이콘을 넣기위해서는 1024*1024 앱 아이콘을 웹상에서 변환해서 넣었는데 Xcode 14 부터는 에셋 appicon 의 인스펙터에서  `single size` 로 정해주면 자동으로 맞게 조정해준다고 합니다.
@yangsubinn @L-j-h-c 진행할까용? 어떻게 생각하세용?
## 📝 To-do

- [x] asset 에서 설정

참고: https://zeddios.tistory.com/1358

**Comment by L-j-h-c** [comment]
@hyun99999 당근 좋습니다~~ 좋은 정보 감사합니다!!

**Comment by yangsubinn** [comment]
우왕 좋습니다! 감사합니다아
